# Generated by Django 3.0.2 on 2020-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_utterance1'),
    ]

    operations = [
        migrations.CreateModel(
            name='KR_MainAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('language', models.CharField(max_length=20)),
                ('mainAction', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
